version: '3'

services:
  nginx:
    image: nginx:1.13-alpine
    ports:
      - 80:80
    volumes:
      - ./build/nginx/nginx.conf:/etc/nginx/nginx.conf
      - .:/api
    depends_on:
      - php
      - mysql

  php:
    build: ./build/php
    volumes:
      - .:/api
    working_dir: /api

  mysql:
    image: mysql:8
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./db/schema.sql:/docker-entrypoint-initdb.d/1.sql
    environment:
      MYSQL_DATABASE: 'root'
      MYSQL_ROOT_PASSWORD: 'root'